wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1678744481.098277
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.13.11
      8:
      - 1
      - 5
cv:
  desc: null
  value: null
error_score:
  desc: null
  value: null
estimator:
  desc: null
  value: DecisionTreeClassifier()
estimator__ccp_alpha:
  desc: null
  value: 0.0
estimator__class_weight:
  desc: null
  value: null
estimator__criterion:
  desc: null
  value: gini
estimator__max_depth:
  desc: null
  value: null
estimator__max_features:
  desc: null
  value: null
estimator__max_leaf_nodes:
  desc: null
  value: null
estimator__min_impurity_decrease:
  desc: null
  value: 0.0
estimator__min_samples_leaf:
  desc: null
  value: 1
estimator__min_samples_split:
  desc: null
  value: 2
estimator__min_weight_fraction_leaf:
  desc: null
  value: 0.0
estimator__random_state:
  desc: null
  value: null
estimator__splitter:
  desc: null
  value: best
n_iter:
  desc: null
  value: 10
n_jobs:
  desc: null
  value: null
param_distributions:
  desc: null
  value:
    ccp_alpha:
    - 0
    - 0.01
    - 0.1
    - 1
    criterion:
    - gini
    - entropy
    - log_loss
    max_features:
    - auto
    - sqrt
    - log2
pre_dispatch:
  desc: null
  value: 2*n_jobs
random_state:
  desc: null
  value: 0
refit:
  desc: null
  value: true
return_train_score:
  desc: null
  value: false
scoring:
  desc: null
  value: null
verbose:
  desc: null
  value: 0
